# pytorch-basics

Use the "Run" button to execute the code.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [3]:
# Execute this to save new versions of the notebook
jovian.commit(project="pytorch-basics")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "adityahebbarnhnm/pytorch-basics" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/adityahebbarnhnm/pytorch-basics


'https://jovian.ai/adityahebbarnhnm/pytorch-basics'

In [4]:
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu


In [5]:
import torch

In [6]:
#Tensors
t1 = torch.tensor(4)
t1

tensor(4)

In [7]:
t1.dtype

torch.int64

In [8]:
#vector
t2 = torch.tensor([1.,2,3,4])
t2.dtype

torch.float32

In [9]:
#Matrix
t3 = torch.tensor([[5,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [10]:
#3-dimentional
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,15]],
                   [[15,16,17],
                    [17,18,19]]
                  ])
t4.shape

torch.Size([2, 2, 3])

In [11]:
#create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
#arithmetic operations
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
#Compute derivative
y.backward()

In [14]:
#display gradients
print('dy/dx :',x.grad)
print('dy/dw :',w.grad)
print('dy/db :', b.grad)

dy/dx : None
dy/dw : tensor(3.)
dy/db : tensor(1.)


In [15]:
import numpy as np

In [16]:
x = np.array([[1,2],[3,4]])

In [17]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [18]:
!pip install jovian --upgrade --quiet

In [19]:
import jovian

In [20]:
# Execute this to save new versions of the notebook
jovian.commit(project="pytorch-basics")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "adityahebbarnhnm/pytorch-basics" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/adityahebbarnhnm/pytorch-basics


'https://jovian.ai/adityahebbarnhnm/pytorch-basics'

## Linear Regression

yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

In [21]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [22]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [23]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [24]:
#weights and biases
w = torch.randn(2,3,requires_grad = True)
b = torch.randn(2, requires_grad = True)

In [25]:
w

tensor([[ 0.0333, -0.9860,  2.0490],
        [ 0.7039, -0.3906,  1.1664]], requires_grad=True)

In [26]:
b

tensor([0.7290, 0.3755], requires_grad=True)

In [27]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [28]:
def model(x):
    return x @ w.t() + b

In [29]:
preds = model(inputs)
print(preds)

tensor([[ 25.2004,  75.7509],
        [ 48.1216, 104.7146],
        [ -9.6630,  76.9345],
        [ 37.5356,  98.5399],
        [ 51.7957,  93.1021]], grad_fn=<AddBackward0>)


In [30]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [31]:
loss = mse(preds, targets)
print(loss)

tensor(2909.5068, grad_fn=<DivBackward0>)


## Gradient

In [32]:
print(w)
print(w.grad)

tensor([[ 0.0333, -0.9860,  2.0490],
        [ 0.7039, -0.3906,  1.1664]], requires_grad=True)
None
